name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
    path: ../
  google_sign_in:
    path: ../../google_sign_in
  material_icons_font: ^0.1.1

flutter:
  uses-material-design: true
