name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
    path: ../
  firebase_messaging:
    path: /Users/Siva/plugin/packages/firebase_messaging
  google_sign_in:
    path: /Users/Siva/plugin/packages/google_sign_in


flutter:
  uses-material-design: true
