name: android_alarm_manager_example
description: Example tests for Android alarm manager.

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager:
    path: ../../
  path_provider: ^1.3.1
  e2e: ^0.2.1
  shared_preferences: ^0.5.6

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
