name: shared_preferences_example
description: Demonstrates how to use the shared_preferences plugin.

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
    path: ../../shared_preferences/
  shared_preferences_linux:
    path: ../

flutter:
  uses-material-design: true

