name: sensors_example
description: Demonstrates how to use the sensors plugin.

dependencies:
  flutter:
    sdk: flutter
  sensors:
    path: ../
  material_icons_font: ^0.1.1

flutter:
  uses-material-design: true
