name: path_provider_example
description: Demonstrates how to use the path_provider plugin.

dependencies:
  flutter:
    sdk: flutter
  path_provider:
    path: ../
  material_icons_font: ^0.1.1

flutter:
  uses-material-design: true
