# Describes the targets run in continuous integration environment.
#
# Flutter infra uses this file to generate a checklist of tasks to be performed
# for every commit.
#
# More information at:
#  * https://github.com/flutter/cocoon/blob/master/CI_YAML.md
enabled_branches:
  - master

platform_properties:
  linux:
    properties:
      caches: >-
        [
        ]
      dependencies: >
        [
          {"dependency": "curl"}
        ]
      device_type: none
      os: Linux
  windows:
    properties:
      caches: >-
        [
          {"name": "vsbuild", "path": "vsbuild"},
          {"name": "pub_cache", "path": ".pub-cache"}
        ]
      dependencies: >
        [
          {"dependency": "certs"}
        ]
      device_type: none
      os: Windows

targets:
  # TODO(stuartmorgan) Remove once the renamed version below has propagated.
  - name: Windows Plugins master channel
    recipe: plugins/plugins
    timeout: 30
    properties:
      add_recipes_cq: "true"
      target_file: windows_build_and_platform_tests.yaml
      dependencies: >
        [
          {"dependency": "vs_build"}
        ]
    scheduler: luci

  # TODO(stuartmorgan) Remove once the renamed version below has propagated.
  - name: Windows Plugins stable channel
    recipe: plugins/plugins
    timeout: 30
    properties:
      add_recipes_cq: "true"
      target_file: windows_build_and_platform_tests.yaml
      channel: stable
      dependencies: >
        [
          {"dependency": "vs_build"}
        ]
    scheduler: luci

  - name: windows-build+platform-tests master
    recipe: plugins/plugins
    bringup: true
    timeout: 30
    properties:
      # TODO(stuartmorgan): Uncomment when removing bringup.
      #add_recipes_cq: "true"
      target_file: windows_build_and_platform_tests.yaml
      dependencies: >
        [
          {"dependency": "vs_build"}
        ]
    scheduler: luci

  - name: windows-build+platform-tests stable
    recipe: plugins/plugins
    bringup: true
    timeout: 30
    properties:
      # TODO(stuartmorgan): Uncomment when removing bringup.
      #add_recipes_cq: "true"
      target_file: uwp_build_and_platform_tests.yaml
      channel: stable
      dependencies: >
        [
          {"dependency": "vs_build"}
        ]
    scheduler: luci

  - name: build_all_plugins_windows master
    recipe: plugins/plugins
    bringup: true
    timeout: 30
    properties:
      # TODO(stuartmorgan): Uncomment when removing bringup.
      #add_recipes_cq: "true"
      target_file: build_all_plugins.yaml
      dependencies: >
        [
          {"dependency": "vs_build"}
        ]
    scheduler: luci

  - name: build_all_plugins_windows stable
    recipe: plugins/plugins
    bringup: true
    timeout: 30
    properties:
      # TODO(stuartmorgan): Uncomment when removing bringup.
      #add_recipes_cq: "true"
      target_file: build_all_plugins.yaml
      channel: stable
      dependencies: >
        [
          {"dependency": "vs_build"}
        ]
    scheduler: luci

  - name: uwp-build+platform-tests master
    recipe: plugins/plugins
    bringup: true
    timeout: 30
    properties:
      # TODO(stuartmorgan): Uncomment when removing bringup.
      #add_recipes_cq: "true"
      target_file: uwp_build_and_platform_tests.yaml
      dependencies: >
        [
          {"dependency": "vs_build"}
        ]
    scheduler: luci

  - name: plugin_tools_tests - Windows
    recipe: plugins/plugins
    bringup: true
    timeout: 30
    properties:
      # TODO(stuartmorgan): Uncomment when removing bringup.
      #add_recipes_cq: "true"
      target_file: plugin_tools_tests.yaml
    scheduler: luci

  - name: Linux ci_yaml plugins roller
    recipe: infra/ci_yaml
    timeout: 30
    scheduler: luci
    runIf:
      - .ci.yaml
