task:
  container:
    image: gcr.io/flutter-cirrus/build-plugins-image:latest
  env:
    CIRRUS_WORKING_DIR: "/opt/flutter plugins"
    # PATH, PUB_CACHE, and FLUTTER_ROOT are set in Dockerfile.
  pub_cache:
    folder: "$PUB_CACHE"
    fingerprint_script:
     - echo $OS
     - grep -r --include=pubspec.yaml 'PUBSPEC CHECKSUM' "$FLUTTER_ROOT"
     - find "$CIRRUS_WORKING_DIR" -type f -name pubspec.yaml -print0 | xargs -0 shasum
  flutter_pkg_cache:
    folder: "$FLUTTER_ROOT/bin/cache/pkg"
    fingerprint_script: echo $OS; cat "$FLUTTER_ROOT/bin/internal/engine.version"
  artifacts_cache:
    folder: "$FLUTTER_ROOT/bin/cache/artifacts"
    fingerprint_script: echo $OS; cat "$FLUTTER_ROOT/bin/internal/engine.version"
  git_fetch_script:
    - git fetch origin
    - git fetch origin master # To set FETCH_HEAD
  upgrade_script:
    - flutter channel master
    - flutter upgrade
    - flutter update-packages
  matrix:
    - name: analyze
      script: ./script/incremental_build.sh analyze
    - name: format
      format_script: ./script/incremental_build.sh format --travis --clang-format=clang-format-5.0
    - name: test-linux
      test_script: ./script/incremental_build.sh test
    - name: build-apks+java-test
      env:
        matrix:
          PLUGIN_SHARDING: "--shardIndex 0 --shardCount 2"
          PLUGIN_SHARDING: "--shardIndex 1 --shardCount 2"
      script:
      - ./script/incremental_build.sh build-examples --apk
      - ./script/incremental_build.sh java-test  # must come after apk build

task:
  name: build-ipas
  osx_instance:
    image: high-sierra-xcode-9.4.1
  env:
    CIRRUS_WORKING_DIR: "/tmp/flutter plugins"
    FLUTTER_ROOT: "/tmp/flutter sdk"
    PUB_CACHE: "/tmp/pub-cache"
    PATH: "$FLUTTER_ROOT/bin:$FLUTTER_ROOT/bin/cache/dart-sdk/bin:$PATH:/usr/local/bin"
    matrix:
      PLUGIN_SHARDING: "--shardIndex 0 --shardCount 2"
      PLUGIN_SHARDING: "--shardIndex 1 --shardCount 2"
  depends_on:
    - analyze
    - format
  git_fetch_script:
    - git fetch origin
    - git fetch origin master # To set FETCH_HEAD
  install_script:
    - brew update
    - brew install libimobiledevice
    - brew install ideviceinstaller
    - brew install ios-deploy
    - pod repo update
    - gem update cocoapods
    - mkdir --parents "$FLUTTER_ROOT"
    - git clone https://github.com/flutter/flutter.git "$FLUTTER_ROOT"
    - flutter channel master
    - flutter upgrade
    - flutter doctor -v
    - pub global activate flutter_plugin_tools
#  pub_cache:
#    folder: "$PUB_CACHE"
#    fingerprint_script:
#     - echo $OS
#     - grep -r --include=pubspec.yaml 'PUBSPEC CHECKSUM' "$FLUTTER_ROOT"
#  flutter_pkg_cache:
#    folder: "$FLUTTER_ROOT/bin/cache/pkg"
#    fingerprint_script: echo $OS; cat "$FLUTTER_ROOT/bin/internal/engine.version"
#  artifacts_cache:
#    folder: "$FLUTTER_ROOT/bin/cache/artifacts"
#    fingerprint_script: echo $OS; cat "$FLUTTER_ROOT/bin/internal/engine.version"
  build_ipas_script:
    - ./script/incremental_build.sh build-examples --ipa
