task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  osx_instance:
    image: mojave-xcode-11.2.1-flutter
  setup_script:
    - pod repo update
  upgrade_script:
    - flutter channel master
    - flutter upgrade
    - git fetch origin master
  activate_script: pub global activate flutter_plugin_tools
  matrix:
    - name: build_all_plugins_ipa
      script:
        - flutter channel master
        - flutter config --enable-macos-desktop
        - ./script/build_all_plugins_app.sh macos
    - name: lint_darwin_plugins
      script: ./script/lint_darwin_plugins.sh
    - name: build-apps+drive-examples
      env:
        PATH: $PATH:/usr/local/bin
        matrix:
          PLUGIN_SHARDING: "--shardIndex 0 --shardCount 4"
          PLUGIN_SHARDING: "--shardIndex 1 --shardCount 4"
          PLUGIN_SHARDING: "--shardIndex 2 --shardCount 4"
          PLUGIN_SHARDING: "--shardIndex 3 --shardCount 4"
        SIMCTL_CHILD_MAPS_API_KEY: ENCRYPTED[596a9f6bca436694625ac50851dc5da6b4d34cba8025f7db5bc9465142e8cd44e15f69e3507787753accebfc4910d550]
      build_script:
        - flutter channel master
        - flutter config --enable-macos-desktop
        - ./script/incremental_build.sh drive-examples

