task:
  name: debug-gradle
  container:
    image: cirrusci/flutter:latest
    cpu: 4
    memory: 8G
  script:
    - echo "current locale"
    - locale
      # - echo "Available locales:"
      # - locale -a
      # - sudo localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
      # - echo "Available locales:"
      # - locale -a
      # - export LANG="en_US.UTF-8" # also tried "en_US.utf8"
      # - export LC_ALL="en_US.UTF-8"
      # - export LANGUAGE="en_US:en"
      # - locale
      # - echo "$CIRRUS_CHANGE_MESSAGE" > /tmp/cirrus_change_message.txt
      # - echo "$CIRRUS_COMMIT_MESSAGE" > /tmp/cirrus_commit_message.txt
      # - echo $CIRRUS_CHANGE_MESSAGE
      # - echo $CIRRUS_COMMIT_MESSAGE
      # - export CIRRUS_CHANGE_MESSAGE=""
      # - export CIRRUS_COMMIT_MESSAGE=""
      # - echo $CIRRUS_CHANGE_MESSAGE
      # - echo $CIRRUS_COMMIT_MESSAGE
    - cd packages/google_maps_flutter/example
    - flutter build apk
      # - android/gradlew app:properties    
      # - export CIRRUS_CHANGE_MESSAGE=`cat /tmp/cirrus_change_message.txt`
      # - export CIRRUS_COMMIT_MESSAGE=`cat /tmp/cirrus_commit_message.txt`
      # - echo $CIRRUS_CHANGE_MESSAGE
      # - echo $CIRRUS_COMMIT_MESSAGE
