task:
  # don't run on release tags since it creates O(n^2) tasks where n is the number of plugins
  only_if: $CIRRUS_TAG == ''
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  container:
    dockerfile: .ci/Dockerfile-LinuxDesktop
    cpu: 8
    memory: 16G
  env:
    E2E_PATH: "./packages/e2e"
  upgrade_script:
    - flutter channel master
    - flutter upgrade
    - git fetch origin master
  matrix:
    - name: verbose-linux-build
      install_script:
        - flutter config --enable-linux-desktop
      build_script:
        - cd packages/path_provider/path_provider_linux/example
        - flutter create .
        - flutter build linux --debug -v
        - flutter build linux -v
