flutter_template: &FLUTTER_TEMPLATE
  upgrade_script:
    - which flutter
    - flutter channel $CHANNEL
    - date
    - flutter upgrade
    - git fetch origin master
    - date
  activate_script:
    - date
    - pub global activate flutter_plugin_tools
    - date

flutter_master_template: &FLUTTER_MASTER_TEMPLATE
  environment:
    CHANNEL: "master"
  << : *FLUTTER_TEMPLATE

flutter_stable_template: &FLUTTER_STABLE_TEMPLATE
  environment:
    CHANNEL: "stable"
  << : *FLUTTER_TEMPLATE

flutter_stable_skip_web_template: &FLUTTER_STABLE_SKIP_WEB_TEMPLATE
  << : *FLUTTER_STABLE_TEMPLATE
  remove_web_plugins_script:
    # TODO(jackson): Allow web plugins once supported on stable
    # https://github.com/flutter/flutter/issues/42864
    - find . | grep _web$ | xargs rm -rf; fi

task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  container:
    dockerfile: .ci/Dockerfile
    cpu: 8
    memory: 16G
  environment:
    PATH: $PATH:$HOME/.pub-cache/bin
  matrix:
    - name: publishable
      << : *FLUTTER_STABLE_TEMPLATE
      script:
        - date
        - ./script/check_publish.sh
        - date
    - name: format
      pub_cache:
        folder: $HOME/.pub-cache
        fingerprint_script: echo $CIRRUS_OS
      flutter_pkg_cache:
        folder: $FLUTTER_HOME/bin/cache/pkg
        fingerprint_script: echo $CIRRUS_OS; cat $FLUTTER_HOME/bin/internal/*.version
      flutter_artifacts_cache:
        folder: $FLUTTER_HOME/bin/cache/artifacts
        fingerprint_script: echo $CIRRUS_OS; cat $FLUTTER_HOME/bin/internal/*.version
      << : *FLUTTER_STABLE_TEMPLATE
      install_script:
        - date
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main"
        - sudo apt-get update
        - sudo apt-get install -y --allow-unauthenticated clang-format-7
        - date
      format_script:
        - date
        - ./script/incremental_build.sh format --travis --clang-format=clang-format-7
        - date
    - name: test
      matrix:
        - << : *FLUTTER_MASTER_TEMPLATE
        - << : *FLUTTER_STABLE_SKIP_WEB_TEMPLATE
      test_script:
        - date
        - ./script/incremental_build.sh test
        - date
    - name: analyze
      << : *FLUTTER_STABLE_TEMPLATE
      script:
        - date
        - ./script/incremental_build.sh analyze
        - date        
    - name: build_all_plugins_apk
      << : *FLUTTER_STABLE_SKIP_WEB_TEMPLATE
      script:
        - date
        - ./script/build_all_plugins_app.sh apk
        - date
      depends_on:
        - format
        - publishable
    - name: build-apks+java-test+firebase-test-lab
      environment:
        matrix:
          PLUGIN_SHARDING: "--shardIndex 0 --shardCount 2"
          PLUGIN_SHARDING: "--shardIndex 1 --shardCount 2"
        matrix:
          - << : *FLUTTER_MASTER_TEMPLATE
          - << : *FLUTTER_STABLE_SKIP_WEB_TEMPLATE
        MAPS_API_KEY: ENCRYPTED[596a9f6bca436694625ac50851dc5da6b4d34cba8025f7db5bc9465142e8cd44e15f69e3507787753accebfc4910d550]
        GCLOUD_FIREBASE_TESTLAB_KEY: ENCRYPTED[07586610af1fdfc894e5969f70ef2458341b9b7e9c3b7c4225a663b4a48732b7208a4d91c3b7d45305a6b55fa2a37fc4]
      script:
        - date
        # Unsetting CIRRUS_CHANGE_MESSAGE and CIRRUS_COMMIT_MESSAGE as they
        # might include non-ASCII characters which makes Gradle crash.
        # See: https://github.com/flutter/flutter/issues/24935
        # This is a temporary workaround until we figure how to properly configure
        # a UTF8 locale on Cirrus (or until the Gradle bug is fixed).
        # TODO(amirh): Set the locale to UTF8.
        - echo "$CIRRUS_CHANGE_MESSAGE" > /tmp/cirrus_change_message.txt
        - echo "$CIRRUS_COMMIT_MESSAGE" > /tmp/cirrus_commit_message.txt
        - export CIRRUS_CHANGE_MESSAGE=""
        - export CIRRUS_COMMIT_MESSAGE=""
        - ./script/incremental_build.sh build-examples --apk
        - ./script/incremental_build.sh java-test  # must come after apk build
        - if [[ $GCLOUD_FIREBASE_TESTLAB_KEY == ENCRYPTED* ]]; then
        -   echo "This user does not have permission to run Firebase Test Lab tests."
        - else
        -   echo $GCLOUD_FIREBASE_TESTLAB_KEY > ${HOME}/gcloud-service-key.json
        -   ./script/incremental_build.sh firebase-test-lab
        - fi
        - export CIRRUS_CHANGE_MESSAGE=`cat /tmp/cirrus_change_message.txt`
        - export CIRRUS_COMMIT_MESSAGE=`cat /tmp/cirrus_commit_message.txt`
        - date
      depends_on:
        - format
        - publishable

task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  osx_instance:
    image: mojave-flutter
  environment:
    COCOAPODS_DISABLE_STATS: true
    PATH: $PATH:/usr/local/bin:$HOME/.pub-cache/bin
  create_simulator_script:
    - date
    - xcrun simctl list
    - xcrun simctl create Flutter-iPhone com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-13-2 | xargs xcrun simctl boot
    - date
  matrix:
    - name: build_all_plugins_ipa
      << : *FLUTTER_STABLE_SKIP_WEB_TEMPLATE
      script:
        - date
        - ./script/build_all_plugins_app.sh ios --no-codesign
        - date
    - name: lint_darwin_plugins
      << : *FLUTTER_STABLE_SKIP_WEB_TEMPLATE
      script:
        - date
        - ./script/lint_darwin_plugins.sh
        - date
    - name: build-ipas+drive-examples
      environment:
        matrix:
          PLUGIN_SHARDING: "--shardIndex 0 --shardCount 4"
          PLUGIN_SHARDING: "--shardIndex 1 --shardCount 4"
          PLUGIN_SHARDING: "--shardIndex 2 --shardCount 4"
          PLUGIN_SHARDING: "--shardIndex 3 --shardCount 4"
        matrix:
          - << : *FLUTTER_MASTER_TEMPLATE
          - << : *FLUTTER_STABLE_SKIP_WEB_TEMPLATE
        SIMCTL_CHILD_MAPS_API_KEY: ENCRYPTED[596a9f6bca436694625ac50851dc5da6b4d34cba8025f7db5bc9465142e8cd44e15f69e3507787753accebfc4910d550]
      script:
        - date
        - ./script/incremental_build.sh build-examples --ipa
        - ./script/incremental_build.sh drive-examples
        - date
  depends_on:
    - format
    - publishable
