name: firebase_performance_example
description: Demonstrates how to use the firebase_performance plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  http: 0.11.3+17
  flutter:
    sdk: flutter
<<<<<<< HEAD
=======
  firebase_performance:
    path: ../
  firebase_core: ^0.4.0
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD

  firebase_performance:
    path: ../
=======
  flutter_driver:
    sdk: flutter
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

flutter:
  uses-material-design: true
