name: firestore_example
description: Demonstrates how to use the firestore plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_firestore:
    path: ../
  material_icons_font: ^0.1.1

flutter:
  uses-material-design: true
