name: shared_preferences_macos
description: macOS implementation of the shared_preferences plugin.
version: 0.0.1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_macos

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: SharedPreferencesPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.6 < 2.0.0"

dependencies:
  shared_preferences_platform_interface: ^1.0.0
  flutter:
    sdk: flutter
