name: firebase_dynamic_links
description: Flutter plugin for Google Dynamic Links for Firebase, an app solution for creating
  and handling links across multiple platforms.
<<<<<<< HEAD
version: 0.1.0
=======
version: 0.4.0+1

>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_dynamic_links

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
=======
  url_launcher: ^4.2.0
  firebase_core: ^0.4.0
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebasedynamiclinks
    iosPrefix: FLT
    pluginClass: FirebaseDynamicLinksPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.2.4 <2.0.0"
