name: webview_flutter_wkwebview_example
description: Demonstrates how to use the webview_flutter_wkwebview plugin.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # TODO (mvanbeusekom): Replace with pub.dev version once published
  webview_flutter_platform_interface:
    path: ../../webview_flutter_platform_interface
  webview_flutter_wkwebview:
    # When depending on this package from a real application you should use:
    #   webview_flutter_wkwebview: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  pedantic: ^1.10.0

flutter:
  uses-material-design: true