name: path_provider
description: A new flutter plugin project.

flutter:
  plugin:
    androidPackage: io.flutter.plugins.path_provider
    pluginClass: PathProviderPlugin

dependencies:
  flutter:
    sdk: flutter
