name: firebase_ml_vision_example
description: Demonstrates how to use the firebase_ml_vision plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.5.0
  cupertino_icons: ^0.1.2
  firebase_ml_vision:
    path: ../
  firebase_core: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
