name: firebase_ml_vision_example
description: Demonstrates how to use the firebase_ml_vision plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.4.5
  cupertino_icons: ^0.1.2

dev_dependencies:
  firebase_ml_vision:
    path: ../
<<<<<<< HEAD
=======
  firebase_core: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  path: ^1.6.2
  path_provider: ^0.5.0+1
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

flutter:
  uses-material-design: true
  assets:
    - assets/test_face.jpg
    - assets/test_barcode.jpg
    - assets/test_contact_barcode.png
    - assets/test_text.png
