name: device_info_example
description: Demonstrates how to use the device_info plugin.

dependencies:
  flutter:
    sdk: flutter
  device_info:
    path: ../
  material_icons_font: ^0.1.1

flutter:
  uses-material-design: true
