name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android and iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
version: 0.10.5
homepage: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: FLTVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: "^1.0.5"
  video_player_platform_interface: ^1.0.1
  video_player_web: ^0.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"
