name: path_provider_windows
description: Windows implementation of the path_provider plugin
version: 0.0.1
homepage: https://github.com/flutter/plugins/tree/master/packages/path_provider/path_provider_windows

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: PathProviderPlugin
        pluginClass: none

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider_platform_interface: ^1.0.1
  win32: ^1.5.1

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
