name: cloud_functions_example
description: Demonstrates how to use the cloud_functions plugin.
version: 1.0.0+1
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
<<<<<<< HEAD
=======
  cloud_functions:
    path: ..
  firebase_core: ^0.4.0
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_functions:
    path: ..

flutter:
  uses-material-design: true

