name: webview_flutter
description: A WebView Plugin for Flutter.
version: 0.0.1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/webview_flutter

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.plugins.webviewflutter
    pluginClass: WebviewFlutterPlugin
