name: in_app_purchase
description: A Flutter plugin for in-app purchases. Exposes APIs for making in-app purchases through the App Store and Google Play.
homepage: https://github.com/flutter/plugins/tree/master/packages/in_app_purchase
version: 0.6.0

# TODO(mvanbeusekom): Remove when in_app_purchase_platform_interface is published
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  
  in_app_purchase_platform_interface: ^1.0.0
  # TODO(mvanbeusekom): Replace with pub.dev version when in_app_purchase_android is published
  in_app_purchase_android:
    path: ../in_app_purchase_android
  # TODO(mvanbeusekom): Replace with pub.dev version when in_app_purchase_ios is published
  in_app_purchase_ios:
    path: ../in_app_purchase_ios  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.16.0
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0
  plugin_platform_interface: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        default_package: in_app_purchase_android
      ios:
        default_package: in_app_purchase_ios

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
