name: device_info_example
description: Demonstrates how to use the device_info plugin.

dependencies:
  flutter:
    sdk: flutter
  device_info:
    path: ../
  e2e: ^0.6.3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
