name: sensor

version: 0.1.0
description: A Flutter plugin to access the accelerometer and gyroscope sensors.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/sensor

flutter:
  plugin:
    androidPackage: io.flutter.plugins.sensor
    pluginClass: SensorPlugin

dependencies:
  flutter:
    sdk: flutter
