name: quick_actions_example
description: Demonstrates how to use the quick_actions plugin.

dependencies:
  flutter:
    sdk: flutter
  quick_actions:
    path: ../
  material_icons_font: ^0.1.1

flutter:
  uses-material-design: true
