name: firebase_auth
description: Flutter plugin for Firebase Auth, enabling Android and iOS
  authentication using passwords, phone numbers and identity providers
  like Google, Facebook and Twitter.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_auth
<<<<<<< HEAD
version: 0.5.19
=======
version: "0.11.1+3"
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebaseauth
    iosPrefix: FLT
    pluginClass: FirebaseAuthPlugin

dependencies:
  meta: ^1.0.4
<<<<<<< HEAD
=======
  firebase_core: ^0.4.0

>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a
  flutter:
    sdk: flutter

dev_dependencies:
  google_sign_in: ^3.0.4
<<<<<<< HEAD
=======
  firebase_dynamic_links: ^0.3.0
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a
  test: ^1.3.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"
