name: shared_preferences_example
description: Demonstrates how to use the shared_preferences plugin.

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
    path: ../
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test_api: 0.2.2
  test_core: 0.2.1+1
  test: 1.5.3

flutter:
  uses-material-design: true
