name: shared_preferences_example
description: Demonstrates how to use the shared_preferences plugin.

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
    path: ../
  material_icons_font: ^0.1.1

flutter:
  uses-material-design: true
