name: audio_player_example
description: Demonstrates how to use the audio_player plugin.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  audio_player:
    path: ../

flutter:
  uses-material-design: true
  assets:
   - assets/flutter-mark-square-64.png
   - assets/crowd-cheering.mp3
