name: google_sign_in_example
description: Example of Google Sign-In plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in:
    # When depending on this package from a real application you should use:
    #   google_sign_in: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  http: ^0.12.0

dev_dependencies:
  pedantic: ^1.8.0
  e2e:  ^0.2.1
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
