name: share_example
description: Demonstrates how to use the share plugin.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  share:
    path: ../
  path_provider:
    path: ../../path_provider/

dev_dependencies:
  flutter_driver:
    sdk: flutter
  e2e: ^0.2.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.2 <2.0.0"
