name: share_example
description: Demonstrates how to use the share plugin.

dependencies:
  flutter:
    sdk: flutter
  share:
    path: ../
  material_icons_font: ^0.1.1

flutter:
  uses-material-design: true
