name: wrapper_example
description: A new Flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0-34.0.dev <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  pigeon: ^4.0.2
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  pedantic: ^1.10.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.wrapper_example
        pluginClass: WrapperExamplePlugin
        dartPluginClass: WrapperExample
      ios:
        pluginClass: WrapperExamplePlugin
