name: version_checker
version: 1.2.3
description: >-
  Used by flutter plugins ci to ensure that we are
  updating the version number incrementally.
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  git: ^1.0.0
