name: google_sign_in

description: Google Sign-In plugin for Flutter.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/google_sign_in
version: 0.0.6

flutter:
  plugin:
    androidPackage: io.flutter.plugins.googlesignin
    pluginClass: GoogleSignInPlugin
  fonts:
    - family: Roboto
      fonts:
        - asset: resources/fonts/Roboto-Medium.ttf
  assets:
    - resources/google_signin_buttons/btn_google_dark_disabled.png
    - resources/google_signin_buttons/btn_google_dark_focus.png
    - resources/google_signin_buttons/btn_google_dark_normal.png
    - resources/google_signin_buttons/btn_google_dark_pressed.png
    - resources/google_signin_buttons/btn_google_light_disabled.png
    - resources/google_signin_buttons/btn_google_light_focus.png
    - resources/google_signin_buttons/btn_google_light_normal.png
    - resources/google_signin_buttons/btn_google_light_pressed.png
    - resources/google_signin_buttons/btn_google_signin_dark_disabled.png
    - resources/google_signin_buttons/btn_google_signin_dark_focus.png
    - resources/google_signin_buttons/btn_google_signin_dark_normal.png
    - resources/google_signin_buttons/btn_google_signin_dark_pressed.png
    - resources/google_signin_buttons/btn_google_signin_light_disabled.png
    - resources/google_signin_buttons/btn_google_signin_light_focus.png
    - resources/google_signin_buttons/btn_google_signin_light_normal.png
    - resources/google_signin_buttons/btn_google_signin_light_pressed.png

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.4

dev_dependencies:
  mockito: ^2.0.2
  test: 0.12.21

environment:
    sdk: ">=1.8.0 <2.0.0"
