name: firebase_admob_example
description: Demonstrates how to use the firebase_admob plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_admob:
    path: ../
<<<<<<< HEAD
=======
  firebase_core: ^0.4.0
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

flutter:
  uses-material-design: true
