name: firebase_admob_example
description: Demonstrates how to use the firebase_admob plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_admob:
    path: ../
  material_icons_font: ^0.1.1

flutter:
  uses-material-design: true
