name: camera_android_camerax
description: Android implementation of the camera plugin with CameraX.
repository: https://github.com/flutter/plugins/tree/main/packages/camera/camera_android_camerax
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: camera
    platforms:
      android:
        package: com.example.camera_android_camerax
        pluginClass: CameraAndroidCameraxPlugin

dependencies:
  camera_platform_interface: ^2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
