name: camera_android_camerax
description: Android implementation of the camera plugin with CameraX.
repository: https://github.com/flutter/plugins/tree/main/packages/camera/camera_android
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.camera_android_camerax
        pluginClass: CameraAndroidCameraxPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
