name: cloud_functions
description: Flutter plugin for Cloud Functions.
<<<<<<< HEAD
version: 0.0.3
=======
version: 0.4.0
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/cloud_functions

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebase.cloudfunctions.cloudfunctions
    pluginClass: CloudFunctionsPlugin

dependencies:
  meta: ^1.1.6
  flutter:
    sdk: flutter
<<<<<<< HEAD
  firebase_core: ^0.2.2
=======
  firebase_core: ^0.4.0
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.2.4 <2.0.0"
