name: camera_windows
description: A Flutter plugin for getting information about and controlling the camera on Windows.
version: 0.0.1
# TODO: Update next lines to match proper repository and issue_tracker url
#repository: https://github.com/flutter/plugins/tree/master/packages/camera/camera_windows
#issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
# TODO: Remove next line after plugin is ready to be published
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.3"

flutter:
  plugin:
    implements: camera
    platforms:
      windows:
        pluginClass: CameraWindows
        dartPluginClass: CameraWindows

dependencies:
  camera_platform_interface: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
