name: connectivity
description: Flutter plugin for discovering the state of the network (WiFi &
  mobile/cellular) connectivity on Android and iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/connectivity
<<<<<<< HEAD
version: 0.3.1
=======
version: 0.4.3+2
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

flutter:
  plugin:
    androidPackage: io.flutter.plugins.connectivity
    iosPrefix: FLT
    pluginClass: ConnectivityPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
