name: webview_flutter
description: A Flutter plugin that provides a WebView widget on Android and iOS.
repository: https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
version: 2.0.12

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  # TODO (BeMacized): Replace with pub.dev version once published
  webview_flutter_platform_interface:
    path: ../webview_flutter_platform_interface
  # TODO (BeMacized): Replace with pub.dev version once published
  webview_flutter_wkwebview:
    path: ../webview_flutter_wkwebview
  # TODO (BeMacized): Replace with pub.dev version once published
  webview_flutter_android:
    path: ../webview_flutter_android

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
