name: firestore_example
description: Demonstrates how to use the firestore plugin.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
    path: ../
  firebase_core: # "^0.1.2"
    path: ../../firebase_core

flutter:
  uses-material-design: true
