name: firestore_example
description: Demonstrates how to use the firestore plugin.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
    path: ../
<<<<<<< HEAD
  firebase_core: "^0.2.2"
=======
  firebase_core: "^0.4.0"

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

flutter:
  uses-material-design: true
