name: flutter_android_lifecycle
description: Flutter plugin for accessing an Android Lifecycle within other plugins.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/flutter_android_lifecycle
version: 1.0.0

flutter:
  plugin:
    androidPackage: io.flutter.plugins.flutterandroidlifecycle
    pluginClass: FlutterAndroidLifecyclePlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.2.0 <2.0.0"
