name: espresso
description: Java classes for testing Flutter apps using Espresso.
version: 0.0.1
homepage: https://github.com/flutter/plugins/espresso

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.9.1 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.example.espresso
    pluginClass: EspressoPlugin
