name: firebase_performance
description: Flutter plugin for Google Performance Monitoring for Firebase, an app
  measurement solution that monitors traces and HTTP/S network requests on Android and
  iOS.
version: 0.0.1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_performance

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^2.0.2
  test: 0.12.30+4

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebaseperformance
    pluginClass: FirebasePerformancePlugin