name: firebase_performance
description: Flutter plugin for Google Performance Monitoring for Firebase, an app
  measurement solution that monitors traces and HTTP/S network requests on Android and
  iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_performance
<<<<<<< HEAD
version: 0.0.7
=======
version: 0.3.0
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  http: 0.11.3+17
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
=======
  firebase_core: ^0.4.0
  flutter_driver:
    sdk: flutter
  test: any
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebaseperformance
    iosPrefix: FLT
    pluginClass: FirebasePerformancePlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.2.4 <2.0.0"
