name: battery_example
description: Demonstrates how to use the battery plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  battery:
    # When depending on this package from a real application you should use:
    #   battery: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  e2e: ^0.2.1
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
