name: battery_example
description: Demonstrates how to use the battery plugin.

dependencies:
  flutter:
    sdk: flutter
  battery:
    path: ../
  material_icons_font: ^0.1.1

flutter:
  uses-material-design: true
