name: e2e_example
description: Demonstrates how to use the e2e plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.6.7 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  e2e:
    # When depending on this package from a real application you should use:
    #   e2e: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  e2e_macos:
    # When depending on this package from a real application you should use:
    #   e2e_macos: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../e2e_macos
  test: any
  pedantic: ^1.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
