name: camera_example
description: Demonstrates how to use the camera plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  camera:
    path: ../
  path_provider: ^0.5.0
  flutter:
    sdk: flutter
  video_player: ^0.10.0
  permission_handler: ^3.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  device_info: ^0.4.0+2

flutter:
  uses-material-design: true
