name: camera_example
description: Demonstrates how to use the camera plugin.

dependencies:
  path_provider: 0.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  camera:
    path: ../

flutter:
  uses-material-design: true
