name: firebase_in_app_messaging
description: Flutter plugin for Firebase In-App Messaging, which helps you engage users who are actively using your app by sending them targeted and contextual messages that nudge them to complete key in-app actions.
version: 0.0.1

author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_app_messaging

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^0.2.5+1

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebaseinappmessaging
    iosPrefix: FLT
    pluginClass: FirebaseInAppMessagingPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.2.4 <2.0.0"
