name: path_provider_example
description: Demonstrates how to use the path_provider plugin.

dependencies:
  flutter:
    sdk: flutter
  path_provider:
    path: ../

dev_dependencies:
  integration_test:
    path: ../../../integration_test
  flutter_driver:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
