name: url_launcher_web
description: Web platform implementation of url_launcher
homepage: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher_web
# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.2.0-nullsafety

flutter:
  plugin:
    platforms:
      web:
        pluginClass: UrlLauncherPlugin
        fileName: url_launcher_web.dart

dependencies:
  # TODO(mvanbeusekom): Update to use pub.dev once null safety version is published.
  url_launcher_platform_interface: 
    path: ../url_launcher_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # TODO(mvanbeusekom): Update to use pub.dev once null safety version is published.
  url_launcher:
    path: ../url_launcher
  pedantic: ^1.10.0-nullsafety.1
  mockito: ^4.1.1
  integration_test:
    path: ../../integration_test

environment:
  sdk: ">=2.10.0-56.0.dev <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
