name: url_launcher_web
description: Web platform implementation of url_launcher
homepage: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher_web
# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 2.0.0-nullsafety

flutter:
  plugin:
    platforms:
      web:
        pluginClass: UrlLauncherPlugin
        fileName: url_launcher_web.dart

dependencies:
  url_launcher_platform_interface: ^2.0.0-nullsafety
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.0.0-nullsafety.6
  pedantic: ^1.10.0-nullsafety.1
  mockito: ^5.0.0-nullsafety.5
  integration_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.26.0-0" # For integration_test from sdk
