name: path_provider_example
description: Demonstrates how to use the path_provider plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  path_provider: any
  path_provider_macos:
    # When depending on this package from a real application you should use:
    #   path_provider_macos: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  test: any
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
