name: connectivity_windows
description: Windows implementation of the connectivity plugin.
version: 0.0.1
homepage: https://github.com/flutter/plugins/tree/master/packages/connectivity/connectivity_windows

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: none
        dartPluginClass: PathProviderWindows

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_platform_interface: ^2.0.1
  ffi: ^1.0.0
  win32: ^2.0.4

dev_dependencies:
  pedantic: ^1.10.0
