name: quick_actions
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

flutter:
  plugin:
    androidPackage: io.flutter.plugins.quickactions
    pluginClass: QuickActionsPlugin

dependencies:
  flutter:
    sdk: flutter
