name: android_alarm_manager_example
description: Demonstrates how to use the android_alarm_manager plugin.

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager:
    path: ../
  path_provider: ^1.3.1
  shared_preferences: ^0.5.6

dev_dependencies:
  espresso: ^0.0.1+1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
