name: android_alarm_manager_example
description: Demonstrates how to use the android_alarm_manager plugin.

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager:
    path: ../
  shared_preferences: ^0.5.6
  e2e: ^0.2.1
  path_provider: ^1.3.1


dev_dependencies:
  espresso:
    path: ../../espresso
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
