name: local_auth_example
description: Demonstrates how to use the local_auth plugin.

dependencies:
  flutter:
    sdk: flutter
  local_auth:
    path: ../
  material_icons_font: ^0.1.1

flutter:
  uses-material-design: true
