name: file_selector_web_tests
publish_to: none

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  integration_test:
    path: ../../../integration_test
  file_selector_web:
    path: ../
