name: url_launcher
description: Flutter plugin for launching a URL on Android and iOS. Supports
  web, phone, SMS, and email schemes.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
version: 5.3.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.urllauncher
        pluginClass: UrlLauncherPlugin
      ios:
        pluginClass: FLTUrlLauncherPlugin
      web:
        default_package: url_launcher_web

dependencies:
  flutter:
    sdk: flutter
  url_launcher_platform_interface: ^1.0.1
  url_launcher_web: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  mockito: ^4.1.1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"
