name: url_launcher_example
description: Demonstrates how to use the url_launcher plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  url_launcher:
    # When depending on this package from a real application you should use:
    #   url_launcher: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  e2e: "^0.2.0"
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.0

flutter:
  uses-material-design: true
