name: local_auth
description: Local authentication plugin for Flutter.
version: 0.0.1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/local_auth

flutter:
  plugin:
    androidPackage: io.flutter.plugins.localauth
    pluginClass: LocalAuthPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

environment:
  sdk: ">=1.8.0 <2.0.0"
