name: package_info_example
description: Demonstrates how to use the package_info plugin.

dependencies:
  flutter:
    sdk: flutter
  package_info:
    # When depending on this package from a real application you should use:
    #   package_info: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  e2e: "^0.2.1"

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
