name: video_player_macos_example
description: Demonstrates how to use the video_player plugin.
version: 0.0.1
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  video_player:
    path: ../../video_player
  video_player_macos:
    # When depending on this package from a real application you should use:
    #   video_player_macos: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    path: ../../../integration_test
  test: any
  pedantic: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/bumble_bee_captions.srt

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
