name: firestore_example
description: Demonstrates how to use the firestore plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_firestore:
    path: ../
  firebase_auth: 0.2.1

flutter:
  uses-material-design: true
