name: firebase_database_example
description: Demonstrates how to use the firebase_database plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.0.1
  firebase_database:
    path: ../

flutter:
  uses-material-design: true
