name: firebase_database_example
description: Demonstrates how to use the firebase_database plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_database:
    path: ../
<<<<<<< HEAD
  firebase_core: ^0.2.2
=======
  firebase_core: ^0.4.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
>>>>>>> 0f80e7380086ceed3c61c05dc431a41d2c32253a

flutter:
  uses-material-design: true
