name: firebase_database_example
description: Demonstrates how to use the firebase_database plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
    path: ../../firebase_auth
  firebase_database:
    path: ../
  firebase_core:
    path: ../../firebase_core

flutter:
  uses-material-design: true
