
name: battery_example
description: Demonstrates how to use the battery plugin.

dependencies:
  flutter:
    sdk: flutter
  battery: ^1.0.6
  battery_macos:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true